services:
  ambertools:
    build: .
    container_name: ambertools
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    volumes:
      - ./data:/workspace
    working_dir: /workspace
    shm_size: '2gb'
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    command: 
      - /bin/bash
      - -l
      - -c
      - |
        source /opt/miniforge/etc/profile.d/conda.sh
        conda activate AmberTools25
        echo "======================================"
        if command -v jupyter &> /dev/null; then
          echo "🟢 JupyterLab is ready to start"
        else
          echo "🔴 JupyterLab not found"
          exit 1
        fi
        echo "======================================"
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=$(python3 -c "from jupyter_server.auth import passwd; print(passwd('$${JUPYTER_PASSWORD}'))")
